--- #YAML:1.0
name: Net-iTMS
version: 0.04
author:
  - Thomas Sibley, http://zulutango.org:82/
abstract: |-
  For interacting with and retrieving information from the iTunes Music Store
license: unrestricted
requires:
  Compress::Zlib: 0
  Crypt::CBC: 0
  Crypt::Rijndael: 0
  Digest::MD5: 0
  File::MkTemp: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  XML::Twig: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Net::iTMS:
    file: lib/Net/iTMS.pm
    version: 0.09
  Net::iTMS::XML:
    file: lib/Net/iTMS/XML.pm
    version: 0.06
generated_by: Module::Build version 0.22
