--- #YAML:1.0
name: Net-iTMS
version: 0.10
author:
  - Thomas Sibley, http://zulutango.org:82/
abstract: |-
  Interface to the information within the iTunes Music Store (iTMS)
license: unrestricted
requires:
  Compress::Zlib: 0
  Crypt::CBC: 0
  Crypt::Rijndael: 0
  Digest::MD5: 0
  Exporter::Lite: 0
  File::MkTemp: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  XML::Twig: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Net::iTMS:
    file: lib/Net/iTMS.pm
    version: 0.10
  Net::iTMS::Album:
    file: lib/Net/iTMS/Album.pm
    version: 0.10
  Net::iTMS::Artist:
    file: lib/Net/iTMS/Artist.pm
    version: 0.10
  Net::iTMS::Error:
    file: lib/Net/iTMS/Error.pm
    version: 0.01
  Net::iTMS::Genre:
    file: lib/Net/iTMS/Genre.pm
    version: 0.10
  Net::iTMS::Request:
    file: lib/Net/iTMS/Request.pm
    version: 0.10
  Net::iTMS::Search:
    file: lib/Net/iTMS/Search.pm
    version: 0.10
  Net::iTMS::Song:
    file: lib/Net/iTMS/Song.pm
    version: 0.10
generated_by: Module::Build version 0.22
